# Generated by Django 5.2.3 on 2025-06-27 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان اعتبار'),
        ),
    ]
