# Generated by Django 5.2.3 on 2025-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_discount_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='is_staff_reply',
            field=models.BooleanField(default=False),
        ),
    ]
