# Generated by Django 5.2.3 on 2025-07-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_stock',
            field=models.PositiveIntegerField(default=True, verbose_name='تعداد محصولات'),
        ),
    ]
